### ISSUE TITLE
dark mode

### ISSUE THREAD

**Issue by igalic** [edwardtufte/tufte-css#169]
Hey folks,

is there any interest in adding automatic Dark Mode to Tufte CSS?

I tried doing my own naïve implementation:

by switching the main colours:

```css
@media (prefers-color-scheme: dark) {
    body {
      color: #fffff8;
      background-color: #111;        
    }
}
```

which resulted in a blurry mess for links, so here's the overrides I came up with:

```css
@media (prefers-color-scheme: dark) {
  body {
    color: #fffff8;
    background-color: #111;        
  }
    
  a:link::selection,
  a:link::-moz-selection {
    text-shadow: inherit;
    background: inherit;
  }
  a:link, .tufte-underline, .hover-tufte-underline:hover {
    text-decoration: none;
    background:inherit;
    -webkit-background-size: inherit;
    -moz-background-size: inherit;
    background-size: inherit
    background-repeat: no-repeat;
    text-shadow: inherit;
    background-position: inherit;
  }
}
```
