### ISSUE TITLE
<ol> not limited to 45% width, unlike <ul>

### ISSUE THREAD

**Issue by aktau** [edwardtufte/tufte-css#56]
I'm not sure why this discrepancy exists, is it to discourage the use of `<ol>` even more? From `tufte.css`

``` css
ul { width: 45%;
     -webkit-padding-start: 5%;
     -webkit-padding-end: 5%;
     list-style-type: none; }
```

Yet I see no similar stanza for `<ol>`. If this is on purpose I guess I'll just have to overwrite it in my extension file, in that case please close this issue.
